<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Employee;
use App\Models\Department;
use App\Models\EmploymentHistory;
use App\Http\Controllers\LeaveCreditController;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        $controller = new LeaveCreditController();
        $employees = [

            // 1. Sammy Cruz
            [
                'username' => 'sammycruz',
                'department' => 'GSO',

                'first_name' => 'Sammy',
                'middle_name' => 'B',
                'surname' => 'Cruz',

                'id_number' => 'LGU-GSO-001',

                'birthdate' => '1991-01-01',
                'place_of_birth' => 'Sinabbaran, Echague, Isabela',

                'sex' => 'male',
                'civil_status' => 'single',

                'height' => "5'6",
                'weight' => '69',
                'bloodtype' => 'O',

                'highest_educational_attainment' => 'graduated',

                'residential_address' => 'Sinabbran, Echague, Isabela',

                'contact_number' => '09750043348',

                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',

                'employment_status' => 'job_order',
                'position' => 'Encoder',

                'date_hired' => '2015-01-10',
            ],


            // 2. Althea De Leon
            [
                'username' => 'altheadeleon',
                'department' => 'GSO',

                'first_name' => 'Althea',
                'middle_name' => 'C',
                'surname' => 'De Leon',

                'id_number' => 'LGU-GSO-002',

                'birthdate' => '1997-01-01',
                'place_of_birth' => 'Sinabbaran, Echague, Isabela',

                'sex' => 'female',
                'civil_status' => 'single',

                'height' => "5'3",
                'weight' => '59',
                'bloodtype' => 'O',

                'highest_educational_attainment' => 'graduated',

                'residential_address' => 'Sinabbran, Echague, Isabela',

                'contact_number' => '09798043788',

                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',

                'employment_status' => 'job_order',
                'position' => 'Office Staff',

                'date_hired' => '2020-04-06',
            ],


            // 3. Jhonny Aquino
            [
                'username' => 'jhonnyaquino',
                'department' => 'GSO',

                'first_name' => 'Jhonny',
                'middle_name' => 'D',
                'surname' => 'Aquino',

                'id_number' => 'LGU-GSO-003',

                'birthdate' => '1989-02-09',
                'place_of_birth' => 'Gucab, Echague, Isabela',

                'sex' => 'male',
                'civil_status' => 'single',

                'height' => "5'9",
                'weight' => '76',
                'bloodtype' => 'A+',

                'highest_educational_attainment' => 'college',

                'residential_address' => 'Gucab, Echague, Isabela',

                'contact_number' => '09798143788',

                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',

                'employment_status' => 'job_order',
                'position' => 'Office Clerk',

                'date_hired' => '2012-01-06',
            ],


            // 4. Carmela Manzano
            [
                'username' => 'carmelamanzano',
                'department' => 'GSO',

                'first_name' => 'Carmela',
                'middle_name' => 'E',
                'surname' => 'Manzano',

                'id_number' => 'LGU-GSO-004',

                'birthdate' => '1993-08-09',
                'place_of_birth' => 'Soyung, Echague, Isabela',

                'sex' => 'female',
                'civil_status' => 'married',

                'height' => "5'9",
                'weight' => '76',
                'bloodtype' => 'O',

                'highest_educational_attainment' => 'graduated',

                'residential_address' => 'Soyung, Echague, Isabela',

                'contact_number' => '09318143788',

                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',

                'employment_status' => 'casual',
                'position' => 'Admin Aide I',

                'date_hired' => '2023-01-06',
            ],


            // 5. Danilo Espiritu
            [
                'username' => 'daniloespiritu',
                'department' => 'GSO',

                'first_name' => 'Danilo',
                'middle_name' => 'F',
                'surname' => 'Espiritu',

                'id_number' => 'LGU-GSO-005',

                'birthdate' => '1999-01-09',
                'place_of_birth' => 'Mabuhay, Echague, Isabela',

                'sex' => 'male',
                'civil_status' => 'single',

                'height' => "5'9",
                'weight' => '76',
                'bloodtype' => 'O',

                'highest_educational_attainment' => 'graduated',

                'residential_address' => 'Mabuhay, Echague, Isabela',

                'contact_number' => '09318143799',

                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',

                'employment_status' => 'permanent',
                'position' => 'GSO I',

                'date_hired' => '2024-01-06',
            ],

            // 6. Maria Bautista
            [
                'username' => 'mariabautista',
                'department' => 'MACO',
                'first_name' => 'Maria',
                'middle_name' => 'C',
                'surname' => 'Bautista',
                'id_number' => 'LGU-MACO-001',
                'birthdate' => '1994-02-09',
                'place_of_birth' => 'Salay, Echague, Isabela',
                'sex' => 'female',
                'civil_status' => 'single',
                'height' => "5'3",
                'weight' => '56',
                'bloodtype' => 'O',
                'highest_educational_attainment' => 'graduated',
                'residential_address' => 'Salay, Echague, Isabela',
                'contact_number' => '09309843799',
                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',
                'employment_status' => 'job_order',
                'position' => 'Data Encoder',
                'date_hired' => '2014-04-09',
            ],


            // 7. Ramon Perez
            [
                'username' => 'ramonperez',
                'department' => 'MACO',
                'first_name' => 'Ramon',
                'middle_name' => 'D',
                'surname' => 'Perez',
                'id_number' => 'LGU-MACO-002',
                'birthdate' => '1997-01-09',
                'place_of_birth' => 'Dugayung, Echague, Isabela',
                'sex' => 'male',
                'civil_status' => 'single',
                'height' => "5'5",
                'weight' => '56',
                'bloodtype' => 'O',
                'highest_educational_attainment' => 'graduated',
                'residential_address' => 'Salay, Echague, Isabela',
                'contact_number' => '09009843799',
                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',
                'employment_status' => 'permanent',
                'position' => 'MACO I',
                'date_hired' => '2023-01-01',
            ],


            // 8. Rowena Dela Cruz
            [
                'username' => 'rowenadelacruz',
                'department' => 'MACO',
                'first_name' => 'Rowena',
                'middle_name' => 'E',
                'surname' => 'Dela Cruz',
                'id_number' => 'LGU-MACO-003',
                'birthdate' => '1995-01-09',
                'place_of_birth' => 'Soyung, Echague, Isabela',
                'sex' => 'female',
                'civil_status' => 'married',
                'height' => "5'4",
                'weight' => '59',
                'bloodtype' => 'B',
                'highest_educational_attainment' => 'graduated',
                'residential_address' => 'Soyung, Echague, Isabela',
                'contact_number' => '09009843799',
                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',
                'employment_status' => 'job_order',
                'position' => 'IT Support',
                'date_hired' => '2017-08-01',
            ],


            // 9. Edwardo Panganiban
            [
                'username' => 'edwardopanganiban',
                'department' => 'MACO',
                'first_name' => 'Edwardo',
                'middle_name' => 'F',
                'surname' => 'Panganiban',
                'id_number' => 'LGU-MACO-004',
                'birthdate' => '1999-01-09',
                'place_of_birth' => 'Soyung, Echague, Isabela',
                'sex' => 'male',
                'civil_status' => 'single',
                'height' => "5'7",
                'weight' => '59',
                'bloodtype' => 'B',
                'highest_educational_attainment' => 'graduated',
                'residential_address' => 'Soyung, Echague, Isabela',
                'contact_number' => '09009843799',
                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',
                'employment_status' => 'job_order',
                'position' => 'Encoder',
                'date_hired' => '2025-11-09',
            ],
            // 10. Angelita Dizon
            [
                'username' => 'angelitadizon',
                'department' => 'MACO',
                'first_name' => 'Angelita',
                'middle_name' => 'G',
                'surname' => 'Dizon',
                'id_number' => 'LGU-MACO-005',
                'birthdate' => '1995-11-11',
                'place_of_birth' => 'Pagasa, Echague, Isabela',
                'sex' => 'female',
                'civil_status' => 'married',
                'height' => "5'1",
                'weight' => '59',
                'bloodtype' => 'B',
                'highest_educational_attainment' => 'graduated',
                'residential_address' => 'Pagasa, Echague, Isabela',
                'contact_number' => '09009809899',
                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',
                'employment_status' => 'job_order',
                'position' => 'Office Staff',
                'date_hired' => '2019-02-12',
            ],


            // 11. Jose Ocampo
            [
                'username' => 'joseocampo',
                'department' => 'MADO',
                'first_name' => 'Jose',
                'middle_name' => 'D',
                'surname' => 'Ocampo',
                'id_number' => 'LGU-MADO-001',
                'birthdate' => '1997-11-11',
                'place_of_birth' => 'Sinabbran, Echague, Isabela',
                'sex' => 'male',
                'civil_status' => 'single',
                'height' => "5'5",
                'weight' => '59',
                'bloodtype' => 'O',
                'highest_educational_attainment' => 'graduated',
                'residential_address' => 'Sinabbran, Echague, Isabela',
                'contact_number' => '09001234599',
                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',
                'employment_status' => 'casual',
                'position' => 'Administrative Assistant',
                'date_hired' => '2021-05-12',
            ],


            // 12. Carmela Tolentino
            [
                'username' => 'carmelatolentino',
                'department' => 'MADO',
                'first_name' => 'Carmela',
                'middle_name' => 'E',
                'surname' => 'Tolentino',
                'id_number' => 'LGU-MADO-002',
                'birthdate' => '1991-11-11',
                'place_of_birth' => 'Sinabbran, Echague, Isabela',
                'sex' => 'female',
                'civil_status' => 'married',
                'height' => "5'3",
                'weight' => '55',
                'bloodtype' => 'O',
                'highest_educational_attainment' => 'graduated',
                'residential_address' => 'Sinabbran, Echague, Isabela',
                'contact_number' => '09001234599',
                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',
                'employment_status' => 'permanent',
                'position' => 'Administrative Aide I',
                'date_hired' => '2012-05-12',
            ],


            // 13. Danilo Ramoz
            [
                'username' => 'daniloramoz',
                'department' => 'MADO',
                'first_name' => 'Danilo',
                'middle_name' => 'Z',
                'surname' => 'Ramoz',
                'id_number' => 'LGU-MADO-003',
                'birthdate' => '1995-01-11',
                'place_of_birth' => 'Sinabbran, Echague, Isabela',
                'sex' => 'male',
                'civil_status' => 'married',
                'height' => "5'9",
                'weight' => '78',
                'bloodtype' => 'O',
                'highest_educational_attainment' => 'graduated',
                'residential_address' => 'Sinabbran, Echague, Isabela',
                'contact_number' => '09001234599',
                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',
                'employment_status' => 'job_order',
                'position' => 'Administrative Assistant',
                'date_hired' => '2014-01-09',
            ],


            // 14. Rowelson Garcia
            [
                'username' => 'rowelsongarcia',
                'department' => 'MAGO',
                'first_name' => 'Rowelson',
                'middle_name' => 'E',
                'surname' => 'Garcia',
                'id_number' => 'LGU-MAGO-001',
                'birthdate' => '2001-01-11',
                'place_of_birth' => 'Sinabbran, Echague, Isabela',
                'sex' => 'male',
                'civil_status' => 'married',
                'height' => "5'9",
                'weight' => '70',
                'bloodtype' => 'O',
                'highest_educational_attainment' => 'graduated',
                'residential_address' => 'Sinabbran, Echague, Isabela',
                'contact_number' => '09001234599',
                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',
                'employment_status' => 'job_order',
                'position' => 'Agriculture Technician',
                'date_hired' => '2026-02-04',
            ],


            // 15. Edwardo Manalili
            [
                'username' => 'edwardomanalili',
                'department' => 'MAGO',
                'first_name' => 'Edwardo',
                'middle_name' => 'F',
                'surname' => 'Manalili',
                'id_number' => 'LGU-MAGO-002',
                'birthdate' => '1994-04-11',
                'place_of_birth' => 'Sinabbran, Echague, Isabela',
                'sex' => 'male',
                'civil_status' => 'single',
                'height' => "5'9",
                'weight' => '70',
                'bloodtype' => 'O',
                'highest_educational_attainment' => 'graduated',
                'residential_address' => 'Sinabbran, Echague, Isabela',
                'contact_number' => '09001234871',
                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',
                'employment_status' => 'job_order',
                'position' => 'Veterinary Aide I',
                'date_hired' => '2016-04-04',
            ],


            // 16. Catherine Manzano
            [
                'username' => 'catherinemanzano',
                'department' => 'MARKET',
                'first_name' => 'Catherine',
                'middle_name' => 'J',
                'surname' => 'Manzano',
                'id_number' => 'LGU-MARKET-001',
                'birthdate' => '1996-01-12',
                'place_of_birth' => 'Annafunan, Echague, Isabela',
                'sex' => 'female',
                'civil_status' => 'single',
                'height' => "5'3",
                'weight' => '59',
                'bloodtype' => 'A',
                'highest_educational_attainment' => 'graduated',
                'residential_address' => 'Annafunan, Echague, Isabela',
                'contact_number' => '09098904871',
                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',
                'employment_status' => 'job_order',
                'position' => 'Field Inspector',
                'date_hired' => '2017-01-02',
            ],


            // 17. Kenedy Quilang
            [
                'username' => 'kenedyquilang',
                'department' => 'MASO',
                'first_name' => 'Kenedy',
                'middle_name' => 'B',
                'surname' => 'Quilang',
                'id_number' => 'LGU-MASO-001',
                'birthdate' => '1995-01-12',
                'place_of_birth' => 'Pagasa, Echague, Isabela',
                'sex' => 'male',
                'civil_status' => 'single',
                'height' => "5'5",
                'weight' => '59',
                'bloodtype' => 'A',
                'highest_educational_attainment' => 'graduated',
                'residential_address' => 'Pagasa, Echague, Isabela',
                'contact_number' => '09009094871',
                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',
                'employment_status' => 'job_order',
                'position' => 'Forester',
                'date_hired' => '2015-01-10',
            ],
            // 18. Reynaldo Tomas
            [
                'username' => 'reynaldotomas',
                'department' => 'MBO',
                'first_name' => 'Reynaldo',
                'middle_name' => 'H',
                'surname' => 'Tomas',
                'id_number' => 'LGU-MBO-001',
                'birthdate' => '1990-01-12',
                'place_of_birth' => 'Pagasa, Echague, Isabela',
                'sex' => 'male',
                'civil_status' => 'single',
                'height' => "5'5",
                'weight' => '59',
                'bloodtype' => 'A',
                'highest_educational_attainment' => 'graduated',
                'residential_address' => 'Pagasa, Echague, Isabela',
                'contact_number' => '09009094871',
                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',
                'employment_status' => 'job_order',
                'position' => 'Encoder',
                'date_hired' => '2013-01-10',
            ],

            // 19. Jhon Farillon
            [
                'username' => 'jhonfarillon',
                'department' => 'MBPLO',
                'first_name' => 'Jhon',
                'middle_name' => 'C',
                'surname' => 'Farillon',
                'id_number' => 'LGU-MBPLO-001',
                'birthdate' => '1995-06-12',
                'place_of_birth' => 'Sinabbran, Echague, Isabela',
                'sex' => 'male',
                'civil_status' => 'single',
                'height' => "5'8",
                'weight' => '65',
                'bloodtype' => 'O',
                'highest_educational_attainment' => 'graduated',
                'residential_address' => 'Sinabbran, Echague, Isabela',
                'contact_number' => '09693779512',
                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',
                'employment_status' => 'job_order',
                'position' => 'Encoder',
                'date_hired' => '2015-02-07',
            ],

            // 20. Mitz Ignacio
            [
                'username' => 'mitzignacio',
                'department' => 'MCRO',
                'first_name' => 'Mitz',
                'middle_name' => 'F',
                'surname' => 'Ignacio',
                'id_number' => 'LGU-MCRO-001',
                'birthdate' => '1995-06-12',
                'place_of_birth' => 'Salay, Echague, Isabela',
                'sex' => 'male',
                'civil_status' => 'single',
                'height' => "5'8",
                'weight' => '65',
                'bloodtype' => 'O',
                'highest_educational_attainment' => 'graduated',
                'residential_address' => 'Salay, Echague, Isabela',
                'contact_number' => '09693779512',
                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',
                'employment_status' => 'job_order',
                'position' => 'Data Encoder',
                'date_hired' => '2012-03-01',
            ],

            // 21. Shane Paolo Valdez
            [
                'username' => 'shanepaolovaldez',
                'department' => 'MDRRMO',
                'first_name' => 'Shane Paolo',
                'middle_name' => 'K',
                'surname' => 'Valdez',
                'id_number' => 'LGU-MDRRMO-001',
                'birthdate' => '1994-01-12',
                'place_of_birth' => 'Sinabbran, Echague, Isabela',
                'sex' => 'male',
                'civil_status' => 'single',
                'height' => "5'8",
                'weight' => '65',
                'bloodtype' => 'O',
                'highest_educational_attainment' => 'graduated',
                'residential_address' => 'Sinabbran, Echague, Isabela',
                'contact_number' => '09693779512',
                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',
                'employment_status' => 'job_order',
                'position' => 'Rescue Personnel',
                'date_hired' => '2019-03-01',
            ],

            // 22. Jilmar Ferrer
            [
                'username' => 'jilmarferrer',
                'department' => 'MDRRMO',
                'first_name' => 'Jilmar',
                'middle_name' => 'B',
                'surname' => 'Ferrer',
                'id_number' => 'LGU-MDRRMO-002',
                'birthdate' => '1996-04-05',
                'place_of_birth' => 'Sinabbran, Echague, Isabela',
                'sex' => 'male',
                'civil_status' => 'single',
                'height' => "5'8",
                'weight' => '65',
                'bloodtype' => 'O',
                'highest_educational_attainment' => 'graduated',
                'residential_address' => 'Sinabbran, Echague, Isabela',
                'contact_number' => '09693779512',
                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',
                'employment_status' => 'job_order',
                'position' => 'Documentation Staff',
                'date_hired' => '2018-01-09',
            ],
            // 23. Jamby Villarta
            [
                'username' => 'jambyvillarta',
                'department' => 'MENRO',
                'first_name' => 'Jamby',
                'middle_name' => 'F',
                'surname' => 'Villarta',
                'id_number' => 'LGU-MENRO-001',
                'birthdate' => '1996-04-05',
                'place_of_birth' => 'Sinabbran, Echague, Isabela',
                'sex' => 'female',
                'civil_status' => 'single',
                'height' => "5'8",
                'weight' => '65',
                'bloodtype' => 'O',
                'highest_educational_attainment' => 'graduated',
                'residential_address' => 'Sinabbran, Echague, Isabela',
                'contact_number' => '09693779511',
                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',
                'employment_status' => 'job_order',
                'position' => 'Project Assistant',
                'date_hired' => '2014-07-09',
            ],

            // 24. Rolando Gonzales
            [
                'username' => 'rolandogonzales',
                'department' => 'MEO',
                'first_name' => 'Rolando',
                'middle_name' => 'L',
                'surname' => 'Gonzales',
                'id_number' => 'LGU-MEO-001',
                'birthdate' => '1992-04-05',
                'place_of_birth' => 'Sinabbran, Echague, Isabela',
                'sex' => 'male',
                'civil_status' => 'single',
                'height' => "5'8",
                'weight' => '65',
                'bloodtype' => 'O',
                'highest_educational_attainment' => 'graduated',
                'residential_address' => 'Sinabbran, Echague, Isabela',
                'contact_number' => '09693779511',
                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',
                'employment_status' => 'job_order',
                'position' => 'Engineering Assistant',
                'date_hired' => '2013-02-09',
            ],

            // 25. Arnel Mercado
            [
                'username' => 'arnelmercado',
                'department' => 'MHO',
                'first_name' => 'Arnel',
                'middle_name' => 'N',
                'surname' => 'Mercado',
                'id_number' => 'LGU-MHO-001',
                'birthdate' => '1990-04-05',
                'place_of_birth' => 'Sinabbran, Echague, Isabela',
                'sex' => 'male',
                'civil_status' => 'married',
                'height' => "5'8",
                'weight' => '65',
                'bloodtype' => 'O',
                'highest_educational_attainment' => 'graduated',
                'residential_address' => 'Sinabbran, Echague, Isabela',
                'contact_number' => '09693779511',
                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',
                'employment_status' => 'job_order',
                'position' => 'Medical Assistant',
                'date_hired' => '2015-02-09',
            ],

            // 26. Joel Pastor
            [
                'username' => 'joelpastor',
                'department' => 'MHRMO',
                'first_name' => 'Joel',
                'middle_name' => 'P',
                'surname' => 'Pastor',
                'id_number' => 'LGU-MHRMO-001',
                'birthdate' => '1995-01-05',
                'place_of_birth' => 'Soyung, Echague, Isabela',
                'sex' => 'male',
                'civil_status' => 'single',
                'height' => "5'8",
                'weight' => '65',
                'bloodtype' => 'O',
                'highest_educational_attainment' => 'graduated',
                'residential_address' => 'Soyung, Echague, Isabela',
                'contact_number' => '09693779878',
                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',
                'employment_status' => 'job_order',
                'position' => 'Encoder',
                'date_hired' => '2013-09-13',
            ],

            // 27. Jhon Reyes
            [
                'username' => 'jhonreyes',
                'department' => 'MHRMO',
                'first_name' => 'Jhon',
                'middle_name' => 'P',
                'surname' => 'Reyes',
                'id_number' => 'LGU-MHRMO-002',
                'birthdate' => '1998-04-05',
                'place_of_birth' => 'Soyung, Echague, Isabela',
                'sex' => 'male',
                'civil_status' => 'single',
                'height' => "5'8",
                'weight' => '65',
                'bloodtype' => 'O',
                'highest_educational_attainment' => 'graduated',
                'residential_address' => 'Soyung, Echague, Isabela',
                'contact_number' => '09693779878',
                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',
                'employment_status' => 'job_order',
                'position' => 'Data Encoder',
                'date_hired' => '2015-03-13',
            ],

            // 28. Jayson Espiritu
            [
                'username' => 'jaysonespiritu',
                'department' => 'MPDO',
                'first_name' => 'Jayson',
                'middle_name' => 'P',
                'surname' => 'Espiritu',
                'id_number' => 'LGU-MPDO-001',
                'birthdate' => '1995-04-05',
                'place_of_birth' => 'Soyung, Echague, Isabela',
                'sex' => 'male',
                'civil_status' => 'single',
                'height' => "5'8",
                'weight' => '65',
                'bloodtype' => 'O',
                'highest_educational_attainment' => 'graduated',
                'residential_address' => 'Soyung, Echague, Isabela',
                'contact_number' => '09693779878',
                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',
                'employment_status' => 'job_order',
                'position' => 'Planing Assitant',
                'date_hired' => '2015-06-13',
            ],
            // 29. Joy Dizon
            [
                'username' => 'joydizon',
                'department' => 'MSWDO',
                'first_name' => 'Joy',
                'middle_name' => 'R',
                'surname' => 'Dizon',
                'id_number' => 'LGU-MSWDO-001',
                'birthdate' => '1991-04-05',
                'place_of_birth' => 'Soyung, Echague, Isabela',
                'sex' => 'female',
                'civil_status' => 'married',
                'height' => "5'8",
                'weight' => '65',
                'bloodtype' => 'O',
                'highest_educational_attainment' => 'graduated',
                'residential_address' => 'Soyung, Echague, Isabela',
                'contact_number' => '09693779878',
                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',
                'employment_status' => 'job_order',
                'position' => 'Social Worker',
                'date_hired' => '2016-01-21',
            ],

            // 30. Nick Pascual
            [
                'username' => 'nickpascual',
                'department' => 'MTO',
                'first_name' => 'Nick',
                'middle_name' => 'F',
                'surname' => 'Pascual',
                'id_number' => 'LGU-MTO-001',
                'birthdate' => '1999-04-05',
                'place_of_birth' => 'Soyung, Echague, Isabela',
                'sex' => 'male',
                'civil_status' => 'single',
                'height' => "5'8",
                'weight' => '65',
                'bloodtype' => 'O',
                'highest_educational_attainment' => 'graduated',
                'residential_address' => 'Soyung, Echague, Isabela',
                'contact_number' => '09693779878',
                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',
                'employment_status' => 'job_order',
                'position' => 'Data Encoder',
                'date_hired' => '2026-01-12',
            ],

            // 31. Leonardo Meneses
            [
                'username' => 'leonardomeneses',
                'department' => 'MO',
                'first_name' => 'Leonardo',
                'middle_name' => 'P',
                'surname' => 'Meneses',
                'id_number' => 'LGU-MO-001',
                'birthdate' => '1985-04-25',
                'place_of_birth' => 'Soyung, Echague, Isabela',
                'sex' => 'male',
                'civil_status' => 'married',
                'height' => "5'8",
                'weight' => '65',
                'bloodtype' => 'O',
                'highest_educational_attainment' => 'graduated',
                'residential_address' => 'Soyung, Echague, Isabela',
                'contact_number' => '09693779878',
                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',
                'employment_status' => 'elected',
                'position' => 'Municipal Mayor',
                'date_hired' => '2016-10-11',
            ],

            // 32. Mark Soriano
            [
                'username' => 'marksoriano',
                'department' => 'POSU',
                'first_name' => 'Mark',
                'middle_name' => 'A',
                'surname' => 'Soriano',
                'id_number' => 'LGU-POSU-001',
                'birthdate' => '1975-04-21',
                'place_of_birth' => 'Soyung, Echague, Isabela',
                'sex' => 'male',
                'civil_status' => 'married',
                'height' => "5'8",
                'weight' => '65',
                'bloodtype' => 'O',
                'highest_educational_attainment' => 'graduated',
                'residential_address' => 'Soyung, Echague, Isabela',
                'contact_number' => '09693779878',
                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',
                'employment_status' => 'job_order',
                'position' => 'Public Safety Officer',
                'date_hired' => '2017-01-20',
            ],

            // 33. Mark Rama
            [
                'username' => 'markrama',
                'department' => 'VMSBO',
                'first_name' => 'Mark',
                'middle_name' => 'B',
                'surname' => 'Rama',
                'id_number' => 'LGU-VMSBO-001',
                'birthdate' => '1986-04-21',
                'place_of_birth' => 'Soyung, Echague, Isabela',
                'sex' => 'male',
                'civil_status' => 'married',
                'height' => "5'8",
                'weight' => '65',
                'bloodtype' => 'O',
                'highest_educational_attainment' => 'graduated',
                'residential_address' => 'Soyung, Echague, Isabela',
                'contact_number' => '09693779878',
                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',
                'employment_status' => 'elected',
                'position' => 'Municipal Vice Mayor',
                'date_hired' => '2016-10-20',
            ],

            // 34. Kiel Ramom
            [
                'username' => 'kielramon',
                'department' => 'VMSBO',
                'first_name' => 'Kiel',
                'middle_name' => 'C',
                'surname' => 'Ramon',
                'id_number' => 'LGU-VMSBO-002',
                'birthdate' => '1984-04-21',
                'place_of_birth' => 'Soyung, Echague, Isabela',
                'sex' => 'male',
                'civil_status' => 'married',
                'height' => "5'8",
                'weight' => '65',
                'bloodtype' => 'O',
                'highest_educational_attainment' => 'graduated',
                'residential_address' => 'Soyung, Echague, Isabela',
                'contact_number' => '09693779878',
                'umid_id' => '1234-5678901-2',
                'pagibig_id' => '1234-5678-9012',
                'philhealth_number' => '12-345678901-2',
                'psn_number' => '1234-5678-9012',
                'tin_number' => '123-456-789',
                'employment_status' => 'elected',
                'position' => 'Sangguniang Bayan',
                'date_hired' => '2016-10-20',
            ],
        ];

        foreach ($employees as $data) {

            $employee = Employee::create([
                'user_id' => User::where('username', $data['username'])->value('id'),
                'department_id' => Department::where('code', $data['department'])->value('id'),

                'first_name' => $data['first_name'],
                'middle_name' => $data['middle_name'],
                'surname' => $data['surname'],

                'id_number' => $data['id_number'],

                'birthdate' => $data['birthdate'],
                'place_of_birth' => $data['place_of_birth'],

                'sex' => $data['sex'],
                'civil_status' => $data['civil_status'],

                'height' => $data['height'],
                'weight' => $data['weight'],
                'bloodtype' => $data['bloodtype'],

                'highest_educational_attainment' => $data['highest_educational_attainment'],

                'residential_address' => $data['residential_address'],

                'contact_number' => $data['contact_number'],

                'umid_id' => $data['umid_id'],
                'pagibig_id' => $data['pagibig_id'],
                'philhealth_number' => $data['philhealth_number'],
                'psn_number' => $data['psn_number'],
                'tin_number' => $data['tin_number'],

                'employment_status' => $data['employment_status'],
                'position' => $data['position'],

                'date_hired' => $data['date_hired'],

                'is_active' => true,
            ]);

            $controller->initializeSingleEmployeeCredits($employee->id);

            EmploymentHistory::create([
                'employee_id' => $employee->id,
                'previous_position' => null,
                'new_position' => $employee->position,
                'previous_employment_status' => null,
                'new_employment_status' => $employee->employment_status,
                'effective_date' => $employee->date_hired,
                'remarks' => 'Initial employment record',
            ]);
        }
    }
}
